version: '3'

services:
    irods-catalog:
        build:
            context: irods_catalog
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        depends_on:
            - irods-catalog

    omero-db:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=postgres

    omero:
        build:
            context: omero
        environment:
            - CONFIG_omero_db_user=postgres
            - CONFIG_omero_db_pass=postgres
            - CONFIG_omero_db_name=postgres
            - CONFIG_omero_db_host=omero-db
            - CONFIG_omero_db_port=5432
            - ROOTPASS=omero-root-password
        volumes:
            - ${PWD}/omero/Send_to_iRODS.py:/opt/omero/server/Send_to_iRODS.py
        ports:
            - "4063:4063"
            - "4064:4064"
        depends_on:
            - omero-db
