services:
    irods-catalog:
        build:
            context: irods_catalog
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        restart: always
        depends_on:
            - irods-catalog
            - minio

    irods-catalog-consumer:
        build:
            context: irods_catalog_consumer
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        restart: always
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-s3-api:
        image: irods/irods_s3_api:0.3.0
        volumes:
            - ./irods_client_s3_api/config.json:/config.json:ro
        ports:
            - "9000:9000"
        restart: on-failure
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    minio:
        image: minio/minio:RELEASE.2024-09-13T20-26-02Z
        ports:
            - "19000:19000"
            - "19001:19001"
        volumes:
          - ./minio-data:/data
        command: minio server /data
        environment: 
          MINIO_ROOT_USER: irods
          MINIO_ROOT_PASSWORD: irodsadmin
          MINIO_ADDRESS: ":19000"
          MINIO_CONSOLE_ADDRESS: ":19001"

    omero-db:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=postgres

    omero:
        image: openmicroscopy/omero-server:5
        environment:
            - CONFIG_omero_db_user=postgres
            - CONFIG_omero_db_pass=postgres
            - CONFIG_omero_db_name=postgres
            - CONFIG_omero_db_host=omero-db
            - CONFIG_omero_db_port=5432
            - ROOTPASS=omero-root-password
        ports:
            - "4063:4063"
            - "4064:4064"
        depends_on:
            - omero-db
